import { useState } from "react";
import { ArrowUpRight, ChevronDown, Mail, Linkedin, Menu, X, MapPin, Sparkles } from "lucide-react";

const cases = [
 {title:"Event Space Costs & Party Venues",tag:"Commercial intent",result:"719 clicks",metric:"119,451 impressions",detail:"Tracked across June–August 2026. June recorded 433 clicks and average position was 5.2; later snapshots were 7.0 and 8.5.",lesson:"I read clicks, impressions, CTR and position together rather than treating rankings as the only KPI."},
 {title:"Events in Washington, DC in 2026",tag:"Local SEO",result:"19.2 → 8.9",metric:"Average position",detail:"CTR moved from 0.5% to 4.6%, while clicks moved from 5 to 49 across the tracked periods.",lesson:"The diagnosis came first: visibility, SERP messaging and intent alignment can require different actions."},
 {title:"Corporate Event Planner Costs",tag:"Commercial content",result:"85 clicks",metric:"17,958 impressions",detail:"Monthly clicks moved from 19 to 38; average position improved from 9.3 to 7.7. August recorded 38 clicks from 7,481 impressions.",lesson:"Understand the query, build around the decision, connect related content, measure and iterate."}
];
const results=[
 ["Average Wedding Cost","190 clicks","140,755 impressions","Position 3.6–4.4"],
 ["Birthday Party Planner Costs","156 clicks","24,621 impressions","July CTR 1.00%"],
 ["Engagement Party Content","80 clicks","15,564 impressions","Position 6.6–7.5"],
 ["Hidden-Gem Washington, DC Venues","5 → 22 clicks","10.9 → 7.7","Local visibility"],
 ["Venue-Level SEO","49 clicks","1,880 impressions","2.61% CTR"],
 ["Philadelphia wedding venues","22.22% CTR","Local result","Strong engagement"]
];
const content=["Ultimate Guide to Party Venue Rental Costs","How Much Do Event Planners Charge?","Average Wedding Cost in 2026","Event Planners vs. Event Coordinators","greatEvent’s Real-Time Venue Inventory Technology","World Cup Watch Party Venue Costs"];
function Label({n,children}:{n:string;children:React.ReactNode}){return <div className="label"><i/> <small>{n}</small><span/>{children}</div>}
function Metric({v,l,accent=""}:{v:string;l:string;accent?:string}){return <div className={`metric ${accent}`}><strong>{v}</strong><span>{l}</span></div>}
export default function Home(){const [open,setOpen]=useState(0);const [menu,setMenu]=useState(false);return <div className="shell" id="top">
 <aside><a className="brand" href="#top"><b>VB</b><span>SEARCH<br/>NOTES</span></a><div className="rule"/><nav>{[["01","About","#about"],["02","Capabilities","#capabilities"],["03","Case studies","#work"],["04","Process","#process"],["05","Experience","#experience"]].map(x=><a href={x[2]} key={x[2]}><small>{x[0]}</small>{x[1]}</a>)}</nav><footer>SEO & DIGITAL<br/>MARKETING<br/><br/>2026 / IN</footer></aside>
 <div className="main"><header><a className="mobile-brand" href="#top">VB / SEARCH NOTES</a><button onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button>{menu&&<div className="mobile-nav">{[["About","#about"],["Capabilities","#capabilities"],["Case studies","#work"],["Process","#process"],["Experience","#experience"]].map(x=><a href={x[1]} onClick={()=>setMenu(false)} key={x[1]}>{x[0]}</a>)}</div>}<a href="#contact" className="inspect">Inspect the work <ArrowUpRight size={15}/></a></header>
 <main>
 <section className="hero"><div><Label n="00">Portfolio / 2026</Label><p className="kicker">SEO & DIGITAL MARKETING EXECUTIVE</p><h1>I turn <em>search demand</em><br/>into organic growth.</h1><p className="lead">I’m a Digital Marketing Executive specializing in <b>SEO, content strategy, search-intent research, Google Search Console, on-page SEO, technical SEO, local SEO, and organic growth.</b></p><div className="actions"><a className="button" href="#contact">Email me <ArrowUpRight size={16}/></a><a href="#work">View case studies <ArrowUpRight size={15}/></a></div><p className="availability">● Available for SEO Specialist · SEO Executive · SEO Analyst · Digital Marketing · Content SEO · Organic Growth</p></div><div className="hero-card"><div className="card-top">01 / SEARCHLIGHT <span>FIELD REPORT</span></div><div className="signal"><div>SEARCH</div><div>INTENT</div><div>CONTENT</div><strong>→</strong><div>GROWTH</div></div><p><b>Search visibility is only the starting point.</b><br/>Understand the query. Improve the page. Measure what changed.</p></div></section>
 <section className="section" id="snapshot"><div className="heading"><div><Label n="01">Performance snapshot</Label><h2>SEO work backed<br/><em>by real search data.</em></h2></div><p>Figures are based on available greatEvent Search Console/workbook data for the relevant reporting periods.</p></div><div className="metrics"><Metric v="1,952" l="search clicks tracked" accent="accent"/><Metric v="461,018" l="search impressions tracked"/><Metric v="719" l="strongest tracked page clicks"/><Metric v="119,451" l="strongest tracked page impressions"/><Metric v="19.2 → 8.9" l="local SEO position" accent="moss"/><Metric v="0.5% → 4.6%" l="local SEO CTR" accent="moss"/><Metric v="200+" l="SEO articles written / optimized"/></div></section>
 <section className="section" id="about"><Label n="02">About the work</Label><div className="two"><h2>I’m curious about<br/><em>why search works.</em></h2><div><p>At greatEvent, I work across SEO, content marketing, analytics, local search and organic distribution for a US-focused event and venue marketplace.</p><p>I’m comfortable moving from query research to intent mapping, content structure, internal linking, on-page improvements and Search Console analysis. I also explore how content can surface in newer search experiences.</p><div className="note"><Sparkles size={17}/><span>WORKING PRINCIPLE</span><b>Research → intent → build → measure → refresh.</b></div></div></div></section>
 <section className="section" id="capabilities"><Label n="03">Capabilities</Label><div className="cap-grid">{[["Content SEO","Keyword research · SERP analysis · topic clustering · briefs · content refreshes"],["On-page SEO","Titles · meta descriptions · hierarchy · FAQs · CTR · internal linking"],["Technical SEO","Indexation · crawlability · broken links · orphan pages · schema opportunities"],["Local SEO","Location mapping · city pages · venue pages · local intent"],["Analytics","GSC · GA4 · clicks · impressions · CTR · position · reporting"],["Organic distribution","Pinterest · Reddit · audience signals · topic discovery"]].map((x,i)=><article key={x[0]}><small>0{i+1}</small><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
 <section className="section" id="work"><Label n="04">Case studies</Label><div className="heading compact"><h2>Evidence first.<br/><em>Claims second.</em></h2><p>I use documented performance data and avoid unsupported causal claims.</p></div><div className="cases">{cases.map((c,i)=><article className={`case ${open===i?'open':''}`} key={c.title}><button onClick={()=>setOpen(open===i?-1:i)}><span><small>{String(i+1).padStart(2,"0")} / {c.tag}</small><strong>{c.title}</strong></span><span className="case-result">{c.result}<ChevronDown/></span></button>{open===i&&<div className="case-detail"><div><strong>{c.metric}</strong><p>{c.detail}</p></div><div><small>LESSON</small><p>{c.lesson}</p></div></div>}</article>)}</div></section>
 <section className="section"><Label n="05">More SEO results</Label><div className="results">{results.map(r=><div className="result" key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><small>{r[3]}</small></div>)}</div></section>
 <section className="section" id="process"><Label n="06">How I solve SEO problems</Label><div className="heading compact"><h2>I don’t start with<br/><em>the keyword.</em></h2><p>I start with the searcher, then work through a repeatable loop.</p></div><div className="process">{[["Research","What are people actually looking for?"],["Understand intent","What should this page help the user accomplish?"],["Map the opportunity","Why should this page deserve visibility?"],["Build & optimize","Turn research into execution."],["Measure","Did the change actually work?"],["Diagnose","Separate symptoms from causes."],["Iterate","Feed the findings into the next cycle."]].map((x,i)=><div key={x[0]}><small>0{i+1}</small><h3>{x[0]}</h3><b>{x[1]}</b></div>)}</div></section>
 <section className="modern section"><div><Label n="07">AI search & modern SEO</Label><h2>Optimizing for<br/><em>how search is changing.</em></h2><p>Search is no longer limited to the traditional ten blue links. I experiment with concise, direct, evidence-led and semantically complete content that is easy for users and search systems to understand.</p></div><div className="modern-note"><Sparkles/><span>AI SEARCH NOTES</span><b>Useful content is still the strategy.</b><small>AI Overviews · featured snippets · semantic search · AI discovery</small></div></section>
 <section className="section"><Label n="08">Organic distribution</Label><div className="distribution"><div><h2>Pinterest</h2><div className="mini-metrics"><Metric v="243.8K" l="impressions" accent="accent"/><Metric v="1.13K" l="saves"/><Metric v="143.1K" l="audience"/></div><p>Audience and trend signals helped inform content and distribution decisions.</p></div><div className="reddit"><span>REDDIT / BUILT FROM ZERO</span><h3>Listen → validate questions → participate → learn → create better content.</h3></div></div></section>
 <section className="section"><Label n="09">Toolkit</Label><div className="toolkit"><div><b>SEO</b><p>Technical · On-page · Local · Keyword research · Search intent · SERP analysis · Internal linking · Audits · Refreshes</p></div><div><b>ANALYTICS</b><p>Google Search Console · GA4 · CTR analysis · Query analysis · Reporting · Google Sheets / Excel</p></div><div><b>TOOLS</b><p>WordPress / CMS · Screaming Frog · Canva · ChatGPT · Claude · Gemini</p></div></div></section>
 <section className="section" id="experience"><Label n="10">Professional experience</Label><div className="two"><div><h2>Digital Marketing<br/><em>Executive.</em></h2><p className="role">greatEvent · 2024 — Present</p></div><div><p>A US-focused event and venue marketplace. My work combines <b>SEO, content marketing, analytics, local SEO, organic growth and digital distribution.</b></p><ul><li>Research keywords and search intent for US audiences.</li><li>Build topic clusters across event, wedding, venue and pricing topics.</li><li>Analyze Search Console at page and query level.</li><li>Improve internal linking and on-page SEO.</li><li>Explore content for modern search experiences including AI Overviews.</li></ul></div></div></section>
 <section className="section content"><Label n="11">Selected content work</Label><h2>Content isn’t just something<br/><em>I publish. It’s something I optimize.</em></h2><div className="content-list">{content.map((x,i)=><a href="#contact" key={x}><small>0{i+1}</small><b>{x}</b><ArrowUpRight size={17}/></a>)}</div></section>
 <section className="recruiter section"><Label n="12">Recruiter takeaway</Label><div className="two"><div><h2>Strategy + execution<br/><em>+ analysis.</em></h2></div><div><p>I bring hands-on experience rather than purely theoretical SEO knowledge. I’m comfortable moving between <b>keyword research → content strategy → execution → analytics → optimization.</b></p><p>Analytical enough to question the numbers, creative enough to understand the content, practical enough to turn an insight into an action.</p></div></div></section>
 <section className="contact section" id="contact"><div><Label n="13">Currently open to</Label><h2>See the bottleneck.<br/><em>Measure the change.</em></h2><p>SEO Specialist · SEO Executive · SEO Analyst · Digital Marketing Executive · Content SEO · Organic Growth · Growth Marketing</p><div className="location"><MapPin size={16}/> India · Remote</div></div><div className="contact-actions"><a className="button" href="mailto:vinayak.arvind1@gmail.com"><Mail size={16}/> Email me <ArrowUpRight size={16}/></a><a href="https://linkedin.com/in/vinayak-arvind" target="_blank" rel="noreferrer"><Linkedin size={17}/> LinkedIn <ArrowUpRight size={14}/></a></div></section>
 </main><footer className="bottom"><span>Vinayak Baraskar</span><span>SEO & Digital Marketing Executive</span><span>Curious about search. Focused on growth. Always learning.</span></footer></div></div>}
